const express = require("express")
const router = express.Router()
const pageController = require("../controllers/pageController")

router.get("/", pageController.getHome)
router.get("/about", pageController.getAbout)
router.get("/guardians", pageController.getGuardians)
router.get("/admission", pageController.getAdmission)
router.get("/contact", pageController.getContact)
router.get("/creche", pageController.getCreche)
router.get("/pre-nursery", pageController.getPreNursery)
router.get("/prep", pageController.getPrep)
router.get("/nursery", pageController.getNursery)
router.get("/pre-prep", pageController.getPrePrep)
router.get("/secondary", pageController.getSecondary)
router.get("/primary", pageController.getPrimary)
router.get("/vision-and-value", pageController.getVisionAndValues)
router.get("/history-and-heritage", pageController.getHistoryAndHeritage)
router.get("/gallery", pageController.getGallery)
router.get("/upcoming-events", pageController.getUpcomingEvents)
router.get("/school-guild", pageController.getSchoolGuild)
router.get("/mid-term-schedule", pageController.getMidTermSchedule)
router.get("/fees", pageController.getFees)
router.get("/classes", pageController.getClasses)
router.get("/headmaster", pageController.getHeadmaster)

module.exports = router
